let tags = [
    '3D Mapping',
    '3D Printing',
    '5G',
    'AI',
    'AI Collaboration',
    'AR',
    'Agriculture',
    'Analysis',
    'Art',
    'Automation',
    'Automotive',
    'Autonomy',
    'Blockchain',
    'Chatbot',
    'Coaching',
    'Codeless',
    'Composition',
    'Computer Vision',
    'Contextual Awareness',
    'Customer Care',
    'Data Collection',
    'Data Processing',
    'Data Sharing',
    'Decentralisation',
    'Design',
    'Discovery',
    'Edge Computing',
    'Education',
    'Engineering',
    'Extended Reality',
    'Farming',
    'Fraud Detection',
    'Hazard Identification',
    'Homomorphic Encryption',
    'IOT',
    'Image Processing',
    'Image Recognition',
    'Inspection',
    'Insurance',
    'IoT',
    'LIDAR',
    'Language Comprehension',
    'Law',
    'Machine Learning',
    'Manufacturing',
    'Music',
    'Natural Language',
    'Navigation',
    'Neuro-linguistic Programming',
    'Optimisation',
    'Personal Assistant',
    'Personalisation',
    'Presentations',
    'Privacy',
    'Real-time Information',
    'Retail',
    'Robot',
    'Safety',
    'Security',
    'Self-driving',
    'Simulation',
    'Smart Devices',
    'Software',
    'Testing',
    'Tool',
    'Troubleshooting',
    'VR',
    'Virtual Environments',
    'Virtual Reality',
    'Voice-To-Text'
];